language: python

python:
- "2.7"

before_install:
# (currently uses pip v19.3.1 instead of v19.0.3; still supports Python 2.7)
- pip install -U pip

install:
- pip install .
- pip install -r requirements.txt

script:
# (for debugging; why does the import from visaplan.tools.html fail?!)
- python pathinfo.py
- nosetests
